import "server-only";
import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import { getPathname, type AppHref } from "@/i18n/navigation";
import { routing, type Locale } from "@/i18n/routing";
import { optimizedImagePath } from "@/lib/utils/image-url";
import { BRAND, SITE_URL, TITLE_SUFFIX } from "./env";

export const OG_LOCALES: Record<Locale, string> = { sr: "sr_RS", en: "en_US", de: "de_DE" };

/** Default share image, generated by src/app/og-default.png/route.tsx. */
export const DEFAULT_OG_IMAGE = { url: "/og-default.png", width: 1200, height: 630, alt: BRAND };

const TITLE_MAX = 60;
const DESCRIPTION_MAX = 155;

type HrefForPathname = Parameters<typeof getPathname>[0]["href"];

/** Absolute, locale-prefixed URL for an internal route. */
export function absoluteUrl(href: HrefForPathname, locale: Locale): string {
  return `${SITE_URL}${getPathname({ href, locale })}`;
}

/** Absolute URL for an image on the storefront's own domain: WordPress
 * images go through /_next/image, never linked directly. */
export function publicImageUrl(src: string, width: 1080 | 1200 = 1080): string {
  if (src.startsWith("/")) return `${SITE_URL}${src}`;
  if (src.startsWith(SITE_URL)) return src;
  return `${SITE_URL}${optimizedImagePath(src, width)}`;
}

/** Cuts at a word boundary and adds "…" if `text` is longer than `max`. */
export function clamp(text: string, max: number): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[\s,.;:–—-]+$/, "")}…`;
}

/**
 * Title with the brand suffix from the root template when it fits in ~60
 * chars; otherwise the page title alone (clamped), so long product names
 * aren't cut off mid-word by search engines.
 */
function resolveTitle(title: string): Metadata["title"] {
  if (title.length + TITLE_SUFFIX.length <= TITLE_MAX) return title;
  return { absolute: clamp(title, TITLE_MAX) };
}

export interface PageSeo {
  locale: Locale;
  /** Internal route (same shape as <Link href>) — becomes the canonical. */
  href: HrefForPathname;
  title: string;
  /** Rendered as-is when it fits; clamped to ~155 chars otherwise. */
  description: string;
  image?: { url: string; width?: number; height?: number; alt?: string } | null;
  /** Search results, cart, checkout, filtered listings… */
  noindex?: boolean;
  /** Page title is already complete (e.g. the home page) — no suffix. */
  absoluteTitle?: boolean;
  type?: "website" | "article";
  /** Override: canonical points somewhere other than `href` (e.g. a
   * filtered listing → its clean URL). Alternates still follow `href`. */
  canonicalHref?: HrefForPathname;
}

export function buildMetadata(seo: PageSeo): Metadata {
  const description = clamp(seo.description, DESCRIPTION_MAX);
  const url = absoluteUrl(seo.href, seo.locale);
  const canonical = seo.canonicalHref ? absoluteUrl(seo.canonicalHref, seo.locale) : url;
  const languages = Object.fromEntries([
    ...routing.locales.map((l) => [l, absoluteUrl(seo.canonicalHref ?? seo.href, l)]),
    ["x-default", absoluteUrl(seo.canonicalHref ?? seo.href, routing.defaultLocale)],
  ]);
  const image = seo.image?.url ? { ...seo.image, url: publicImageUrl(seo.image.url, 1200) } : DEFAULT_OG_IMAGE;
  const socialTitle = seo.absoluteTitle ? seo.title : `${seo.title}${TITLE_SUFFIX}`;

  return {
    title: seo.absoluteTitle ? { absolute: seo.title } : resolveTitle(seo.title),
    description,
    alternates: { canonical, languages },
    ...(seo.noindex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type: seo.type ?? "website",
      siteName: BRAND,
      url: canonical,
      title: socialTitle,
      description,
      locale: OG_LOCALES[seo.locale],
      alternateLocale: routing.locales.filter((l) => l !== seo.locale).map((l) => OG_LOCALES[l]),
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [image.url],
    },
  };
}

export type { AppHref };

type StaticPageKey = "contact" | "faq" | "shipping" | "becomeInstaller" | "warranty" | "installers" | "installGuide" | "terms";
type StaticNamespace =
  | "ContactPage"
  | "FaqPage"
  | "ShippingReturnsPage"
  | "BecomeInstallerPage"
  | "WarrantyPage"
  | "InstallersPage"
  | "InstallGuidePage"
  | "TermsPage";

/** Metadata for a content page: SEO title from `Seo.pages.<key>`,
 * description from `<namespace>.metaDescription`. */
export async function staticPageMetadata(
  locale: Locale,
  href: Exclude<HrefForPathname, object>,
  key: StaticPageKey,
  namespace: StaticNamespace,
): Promise<Metadata> {
  const [tSeo, tPage] = await Promise.all([
    getTranslations({ locale, namespace: "Seo" }),
    getTranslations({ locale, namespace }),
  ]);
  return buildMetadata({
    locale,
    href,
    title: tSeo(`pages.${key}`),
    description: tPage("metaDescription"),
  });
}
