// GENERATED by scripts/client-messages.mts — do not edit by hand.
// Message namespaces that client components need, per route segment.
export const CLIENT_NAMESPACES = {
  "layout": [
    "CartDrawer",
    "CookieConsent",
    "Footer",
    "Header",
    "ImageSlot",
    "LanguageSwitcher",
    "QuantityStepper",
    "SearchBar"
  ],
  "routes": {
    "": [
      "ImageSlot",
      "KitCarousel"
    ],
    "cesta-pitanja": [],
    "dostava-i-povracaj": [],
    "garancija": [
      "Breadcrumb",
      "Common",
      "WarrantyForm",
      "WarrantyPage"
    ],
    "kasa": [
      "CartLineItem",
      "CheckoutErrors",
      "CheckoutPage",
      "DeliveryForm",
      "ImageSlot",
      "OrderSummary",
      "PaymentMethods"
    ],
    "kategorija": [],
    "kontakt": [
      "Breadcrumb",
      "Common",
      "ContactPage",
      "Site"
    ],
    "korpa": [
      "CartLineItem",
      "CartPage",
      "ImageSlot",
      "OrderSummary",
      "QuantityStepper"
    ],
    "ovlasceni-centri": [
      "Breadcrumb",
      "Common",
      "InstallersPage"
    ],
    "postani-instalater": [
      "BecomeInstallerPage"
    ],
    "potvrda-porudzbine": [
      "CartLineItem",
      "ImageSlot",
      "OrderConfirmationPage"
    ],
    "pretraga": [],
    "proizvod": [
      "ImageSlot",
      "ProductGallery",
      "ProductPurchasePanel",
      "QuantityStepper",
      "StockStatus"
    ],
    "uputstva-za-montazu": [],
    "uslovi-koriscenja": []
  }
} as const;
