/**
 * Computes which next-intl message namespaces client components need, per
 * route, by walking the import graph from each route's page/layout files:
 * every module reachable through a "use client" boundary runs in the
 * browser, and its `useTranslations("X")` calls need namespace X there.
 *
 *   node scripts/client-messages.mts          → rewrite src/i18n/client-messages.generated.ts
 *   node scripts/client-messages.mts --check  → exit 1 if that file is out of date
 *
 * Run by `npm run typecheck`, so a new client component using a new
 * namespace can't silently ship without its messages.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SRC = join(ROOT, "src");
const APP = join(SRC, "app", "[locale]");
const OUT = join(SRC, "i18n", "client-messages.generated.ts");

function resolveImport(from: string, spec: string): string | null {
  let base: string;
  if (spec.startsWith("@/")) base = join(SRC, spec.slice(2));
  else if (spec.startsWith(".")) base = resolve(dirname(from), spec);
  else return null; // package import
  for (const candidate of [base, `${base}.tsx`, `${base}.ts`, join(base, "index.tsx"), join(base, "index.ts")]) {
    if (existsSync(candidate) && statSync(candidate).isFile()) return candidate;
  }
  return null;
}

const cache = new Map<string, { client: boolean; namespaces: string[]; imports: string[] }>();
function parse(file: string) {
  if (!cache.has(file)) {
    const code = readFileSync(file, "utf8");
    const imports = [
      ...code.matchAll(/(?:import|export)\s[^'"]*?from\s+["']([^"']+)["']/g),
      ...code.matchAll(/import\(\s*["']([^"']+)["']\s*\)/g),
    ]
      .map((m) => resolveImport(file, m[1]))
      .filter((f): f is string => f !== null && /\.(tsx?|mts)$/.test(f));
    cache.set(file, {
      client: /^\s*["']use client["']/.test(code),
      namespaces: [...code.matchAll(/useTranslations\(\s*["']([A-Za-z]+)["']\s*\)/g)].map((m) => m[1]),
      imports,
    });
  }
  return cache.get(file)!;
}

/** Namespaces used by client-side modules reachable from the entry files. */
function clientNamespaces(entries: string[]): string[] {
  const found = new Set<string>();
  const seen = new Set<string>();
  const walk = (file: string, inClient: boolean) => {
    const key = `${file}|${inClient}`;
    if (seen.has(key)) return;
    seen.add(key);
    const mod = parse(file);
    const client = inClient || mod.client;
    if (client) mod.namespaces.forEach((n) => found.add(n));
    mod.imports.forEach((dep) => walk(dep, client));
  };
  entries.forEach((e) => walk(e, false));
  return [...found].sort();
}

const entryFiles = (dir: string, recursive: boolean): string[] =>
  readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) return recursive ? entryFiles(path, true) : [];
    return /^(page|layout|not-found|error|loading)\.tsx$/.test(name) ? [path] : [];
  });

// Layout level: everything the root [locale] layout renders around pages,
// plus the not-found page (rendered inside the root provider).
const layout = clientNamespaces([join(APP, "layout.tsx"), join(APP, "not-found.tsx")]);

// Route level: each top-level segment under [locale] ("" = home page).
const routes: Record<string, string[]> = { "": clientNamespaces([join(APP, "page.tsx")]) };
for (const name of readdirSync(APP).sort()) {
  const dir = join(APP, name);
  if (statSync(dir).isDirectory()) routes[name] = clientNamespaces(entryFiles(dir, true));
}

const output =
  `// GENERATED by scripts/client-messages.mts — do not edit by hand.\n` +
  `// Message namespaces that client components need, per route segment.\n` +
  `export const CLIENT_NAMESPACES = ${JSON.stringify({ layout, routes }, null, 2)} as const;\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== output) {
    console.error(`${relative(ROOT, OUT)} is out of date — run: node scripts/client-messages.mts`);
    process.exit(1);
  }
} else {
  writeFileSync(OUT, output);
  console.log(`wrote ${relative(ROOT, OUT)}`);
}
